### ISSUE TITLE
Mod Not Showing Up On ModList Or Ingame

### ISSUE THREAD

**Issue by coolside** [Samtrion/CompactDrawers#5]
Hi, I've been looking for a mod like this and voila!

I've installed this mod into Enigmatica 2 Expert Skyblock and for some reason, it doesn't show ingame mod options nor does it show in JEI.  I have the required libraries for this.

Any Help?

Thanks in advance, 

duG

**Comment by samtrion** [comment]
Hi,

Thanks for your message. I've just installed the ModPack, added CompactDrawers and was able to use it without problems.

Do you play it on a server? Then this also needs CompactDrawers.

**Comment by coolside** [comment]
I see what I did wrong.  When on the projects page, I didn't realize that
the download was for the src.jar version.  I hit the file page and found
what I was looking for.  Sorry to trouble you.

Great mod!

duG

**Comment by samtrion** [comment]
Hey, I'm glad to hear that. Have fun with CompactDrawers
